// Extended Menu Data (110 Items) for NeoBite Restaurant
// All items accurately match downloaded food images for authenticity

export const extendedMenuItems = [
  // === STARTERS (30 items) ===
  // Using: Burgers (1-15), Samosas (101-105), Pizza slices (31-35), Rice (86-90)
  
  { id: 101, category: "Starters", name: "Cosmic Slider Trio", price: "$16", desc: "Three gourmet mini burgers with melted cheese, crispy lettuce, and special sauce on toasted brioche buns.", image: "/assets/menu/food-1.jpg", ingredients: ["Beef Patties", "Brioche Buns", "Cheddar Cheese", "Lettuce", "Tomato", "Special Sauce"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "4.8" },
  { id: 102, category: "Starters", name: "Quantum Quarter Pounder", price: "$18", desc: "Classic cheeseburger with a thick beef patty, melted American cheese, pickles, and tangy burger sauce.", image: "/assets/menu/food-2.jpg", ingredients: ["Beef Patty", "Burger Bun", "American Cheese", "Pickles", "Onions", "Burger Sauce"], allergens: ["Gluten", "Dairy"], rating: "4.7" },
  { id: 103, category: "Starters", name: "Neon Cheeseburger", price: "$14", desc: "Juicy beef burger topped with melted cheddar, fresh lettuce, tomatoes, and mayo on a sesame seed bun.", image: "/assets/menu/food-3.jpg", ingredients: ["Ground Beef", "Sesame Bun", "Cheddar", "Lettuce", "Tomato", "Mayonnaise"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "4.6" },
  { id: 104, category: "Starters", name: "Binary Bacon Burger", price: "$12", desc: "Double beef patties with crispy bacon, cheese, and BBQ sauce in a toasted bun.", image: "/assets/menu/food-4.jpg", ingredients: ["Beef Patties", "Bacon", "Cheese", "BBQ Sauce", "Burger Bun"], allergens: ["Gluten", "Dairy"], rating: "4.9" },
  { id: 105, category: "Starters", name: "Stellar Cheese Stack", price: "$15", desc: "Loaded burger with triple cheese layers, caramelized onions, and garlic aioli.", image: "/assets/menu/food-5.jpg", ingredients: ["Beef", "Cheddar", "Swiss", "Mozzarella", "Onions", "Garlic Aioli"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "4.8" },
  { id: 106, category: "Starters", name: "Meteor Mini Burgers", price: "$17", desc: "Five petite gourmet burgers with various toppings - perfect for sharing.", image: "/assets/menu/food-6.jpg", ingredients: ["Mini Beef Patties", "Slider Buns", "Assorted Cheeses", "Fresh Vegetables"], allergens: ["Gluten", "Dairy"], rating: "4.9" },
  { id: 107, category: "Starters", name: "Photon Cheeseburger Classic", price: "$13", desc: "Traditional American cheeseburger with all the fixings on a soft potato bun.", image: "/assets/menu/food-7.jpg", ingredients: ["Beef", "Potato Bun", "American Cheese", "Ketchup", "Mustard", "Pickles"], allergens: ["Gluten", "Dairy"], rating: "4.7" },
  { id: 108, category: "Starters", name: "Cosmic Deluxe Burger", price: "$11", desc: "Premium burger with fried egg, cheese, bacon, and hash brown on a brioche bun.", image: "/assets/menu/food-8.jpg", ingredients: ["Beef", "Fried Egg", "Bacon", "Cheese", "Hash Brown", "Brioche"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "4.6" },
  { id: 109, category: "Starters", name: "Velocity Veggie Burger", price: "$14", desc: "Plant-based patty with avocado, sprouts, tomato, and vegan mayo on a whole wheat bun.", image: "/assets/menu/food-9.jpg", ingredients: ["Veggie Patty", "Avocado", "Sprouts", "Tomato", "Vegan Mayo", "Whole Wheat Bun"], allergens: ["Gluten"], rating: "4.8" },
  { id: 110, category: "Starters", name: "Warp Double Stack", price: "$13", desc: "Two beef patties stacked high with double cheese, lettuce, and signature sauce.", image: "/assets/menu/food-10.jpg", ingredients: ["Double Beef", "Double Cheese", "Lettuce", "Signature Sauce", "Sesame Bun"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "4.7" },
  
  { id: 111, category: "Starters", name: "Galactic Gourmet Burger", price: "$10", desc: "Artisan burger with blue cheese, arugula, and caramelized onion jam.", image: "/assets/menu/food-11.jpg", ingredients: ["Beef", "Blue Cheese", "Arugula", "Onion Jam", "Artisan Bun"], allergens: ["Gluten", "Dairy"], rating: "4.5" },
  { id: 112, category: "Starters", name: "Nebula Chicken Burger", price: "$15", desc: "Crispy fried chicken breast with coleslaw, pickles, and ranch dressing.", image: "/assets/menu/food-12.jpg", ingredients: ["Breaded Chicken", "Coleslaw", "Pickles", "Ranch", "Potato Bun"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "4.6" },
  { id: 113, category: "Starters", name: "Plasma BBQ Burger", price: "$12", desc: "Smoky BBQ burger with crispy onion rings, bacon, and tangy BBQ sauce.", image: "/assets/menu/food-13.jpg", ingredients: ["Beef", "BBQ Sauce", "Onion Rings", "Bacon", "Cheddar"], allergens: ["Gluten", "Dairy"], rating: "4.4" },
  { id: 114, category: "Starters", name: "Eclipse Turkey Burger", price: "$16", desc: "Lean turkey patty with cranberry relish, brie cheese, and spinach.", image: "/assets/menu/food-14.jpg", ingredients: ["Turkey Patty", "Brie", "Cranberry", "Spinach", "Whole Grain Bun"], allergens: ["Gluten", "Dairy"], rating: "4.9" },
  { id: 115, category: "Starters", name: "Fusion Fish Burger", price: "$11", desc: "Crispy fish fillet with tartar sauce, lettuce, and lemon on a soft bun.", image: "/assets/menu/food-15.jpg", ingredients: ["Fish Fillet", "Tartar Sauce", "Lettuce", "Lemon", "Burger Bun"], allergens: ["Fish", "Gluten", "Eggs"], rating: "4.7" },
  
  { id: 116, category: "Starters", name: "Velocity Veg Samosas", price: "$13", desc: "Crispy triangular pastries filled with spiced potatoes, peas, and aromatic herbs.", image: "/assets/menu/food-101.jpg", ingredients: ["Potatoes", "Peas", "Pastry", "Cumin", "Coriander", "Chili"], allergens: ["Gluten"], rating: "4.6" },
  { id: 117, category: "Starters", name: "Cosmic Keema Samosas", price: "$22", desc: "Golden-fried samosas stuffed with seasoned minced meat and spices.", image: "/assets/menu/food-102.jpg", ingredients: ["Minced Meat", "Pastry", "Onions", "Garam Masala", "Ginger"], allergens: ["Gluten"], rating: "4.8" },
  { id: 118, category: "Starters", name: "Stellar Spinach Samosas", price: "$14", desc: "Flaky pastry pockets filled with spinach, paneer, and mild spices.", image: "/assets/menu/food-103.jpg", ingredients: ["Spinach", "Paneer", "Pastry Dough", "Spices"], allergens: ["Gluten", "Dairy"], rating: "4.9" },
  { id: 119, category: "Starters", name: "Pulsar Party Samosas", price: "$18", desc: "Assorted samosas platter with vegetable, chicken, and paneer varieties.", image: "/assets/menu/food-104.jpg", ingredients: ["Mixed Vegetables", "Chicken", "Paneer", "Pastry", "Spices"], allergens: ["Gluten", "Dairy"], rating: "4.9" },
  { id: 120, category: "Starters", name: "Zodiac Cheese Samosas", price: "$12", desc: "Crispy samosas filled with melted cheese, jalapeños, and herbs.", image: "/assets/menu/food-105.jpg", ingredients: ["Cheese", "Jalapeños", "Pastry", "Cilantro"], allergens: ["Gluten", "Dairy"], rating: "4.5" },

  { id: 121, category: "Starters", name: "Meteor Pizza Bites", price: "$13", desc: "Mini pizza slices with melted mozzarella, pepperoni, and Italian herbs.", image: "/assets/menu/food-31.jpg", ingredients: ["Pizza Dough", "Mozzarella", "Pepperoni", "Tomato Sauce", "Oregano"], allergens: ["Gluten", "Dairy"], rating: "4.7" },
  { id: 122, category: "Starters", name: "Asteroid Appetizer Pizzas", price: "$14", desc: "Four personal-sized pizzas with assorted toppings to share.", image: "/assets/menu/food-32.jpg", ingredients: ["Pizza Base", "Various Cheeses", "Assorted Toppings"], allergens: ["Gluten", "Dairy"], rating: "4.8" },
  { id: 123, category: "Starters", name: "Radiant Rice Bites", price: "$11", desc: "Crispy rice cakes topped with savory toppings and sesame seeds.", image: "/assets/menu/food-86.jpg", ingredients: ["Rice", "Sesame Seeds", "Soy Sauce", "Vegetables"], allergens: ["Soy", "Sesame"], rating: "4.6" },
  { id: 124, category: "Starters", name: "Eclipse Fried Rice Balls", price: "$9", desc: "Golden-fried rice balls stuffed with cheese and herbs.", image: "/assets/menu/food-87.jpg", ingredients: ["Rice", "Cheese", "Herbs", "Breadcrumbs"], allergens: ["Dairy", "Gluten"], rating: "4.4" },
  { id: 125, category: "Starters", name: "Photon Pizza Rolls", price: "$16", desc: "Rolled pizza dough filled with cheese, sauce, and your choice of toppings.", image: "/assets/menu/food-33.jpg", ingredients: ["Pizza Dough", "Cheese", "Pizza Sauce", "Italian Seasoning"], allergens: ["Gluten", "Dairy"], rating: "4.8" },
  { id: 126, category: "Starters", name: "Starlight Snack Pizzas", price: "$20", desc: "Six mini pizzas perfect for appetizers or party snacks.", image: "/assets/menu/food-34.jpg", ingredients: ["Mini Pizza Bases", "Mozzarella", "Tomato", "Basil"], allergens: ["Gluten", "Dairy"], rating: "4.9" },
  { id: 127, category: "Starters", name: "Lunar Rice Crackers", price: "$13", desc: "Crispy rice crackers with spicy dipping sauce.", image: "/assets/menu/food-88.jpg", ingredients: ["Rice Flour", "Salt", "Spices", "Chili Sauce"], allergens: ["Soy"], rating: "4.7" },
  { id: 128, category: "Starters", name: "Orbit Onigiri", price: "$15", desc: "Japanese rice balls wrapped in seaweed with savory fillings.", image: "/assets/menu/food-89.jpg", ingredients: ["Sushi Rice", "Nori", "Pickled Plum", "Sesame"], allergens: ["Soy", "Sesame"], rating: "4.5" },
  { id: 129, category: "Starters", name: "Wormhole Pizza Wedges", price: "$15", desc: "Large pizza slices with loaded toppings - pepperoni, mushrooms, and olives.", image: "/assets/menu/food-35.jpg", ingredients: ["Pizza", "Pepperoni", "Mushrooms", "Olives", "Cheese"], allergens: ["Gluten", "Dairy"], rating: "4.9" },
  { id: 130, category: "Starters", name: "Gravity Rice Wrap", price: "$12", desc: "Savory rice paper rolls filled with vegetables and rice noodles.", image: "/assets/menu/food-90.jpg", ingredients: ["Rice Paper", "Rice Noodles", "Vegetables", "Peanut Sauce"], allergens: ["Peanuts"], rating: "4.4" },

  // === MAINS (40 items) ===
  // Using: Burgers (16-30), Pizza (36-50), Pasta (71-85), Rice (91-95), Biryani (96-100), Curry (111-115)
  
  { id: 201, category: "Mains", name: "Cyber Sushi Platter", price: "$24", desc: "Premium grade sashimi with neon-infused rice, served with holographic wasabi and quantum soy reduction.", image: "/assets/sushi.png", ingredients: ["Tuna", "Salmon", "Yellowtail", "Sushi Rice", "Nori", "Wasabi", "Soy Sauce"], allergens: ["Fish", "Soy", "Gluten"], rating: "5.0" },
  { id: 202, category: "Mains", name: "Quantum Burger", price: "$18", desc: "Wagyu beef patty topped with zero-gravity melted cheese, plasma sauce, and crispy onion rings on a charcoal brioche bun.", image: "/assets/burger.png", ingredients: ["Wagyu Beef", "Aged Cheddar", "Brioche Bun", "Onion Rings", "Special Sauce", "Lettuce", "Tomato"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "4.9" },
  { id: 203, category: "Mains", name: "Nebula Noodles", price: "$22", desc: "Hand-pulled ramen in a rich, void-black truffle broth, topped with bioluminescent mushrooms and soft-boiled solar egg.", image: "/assets/noodles.png", ingredients: ["Hand-Pulled Noodles", "Truffle Oil", "Shiitake Mushrooms", "Soft-Boiled Egg", "Scallions", "Nori"], allergens: ["Gluten", "Eggs", "Soy"], rating: "5.0" },
  
  { id: 204, category: "Mains", name: "Supernova Supreme Burger", price: "$20", desc: "Massive burger with double beef, triple cheese, bacon, and all premium toppings.", image: "/assets/menu/food-16.jpg", ingredients: ["Double Beef", "Triple Cheese", "Bacon", "Onions", "Tomato", "Lettuce"], allergens: ["Gluten", "Dairy"], rating: "4.8" },
  { id: 205, category: "Mains", name: "Galactic Grill Burger", price: "$35", desc: "Flame-grilled burger with roasted peppers, Swiss cheese, and garlic mayo.", image: "/assets/menu/food-17.jpg", ingredients: ["Grilled Beef", "Swiss Cheese", "Roasted Peppers", "Garlic Mayo", "Sourdough Bun"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "5.0" },
  { id: 206, category: "Mains", name: "Void Vegan Burger", price: "$26", desc: "Beyond meat patty with vegan cheese, avocado, and plant-based special sauce.", image: "/assets/menu/food-18.jpg", ingredients: ["Plant-Based Patty", "Vegan Cheese", "Avocado", "Vegan Mayo", "Whole Grain Bun"], allergens: ["Gluten"], rating: "4.8" },
  { id: 207, category: "Mains", name: "Solar Salmon Burger", price: "$28", desc: "Grilled salmon patty with dill cream cheese and cucumber on a pretzel bun.", image: "/assets/menu/food-19.jpg", ingredients: ["Salmon", "Dill Cream Cheese", "Cucumber", "Pretzel Bun"], allergens: ["Fish", "Gluten", "Dairy"], rating: "4.9" },
  { id: 208, category: "Mains", name: "Cosmic Chicken Burger", price: "$21", desc: "Grilled chicken breast with Swiss cheese, bacon, and honey mustard.", image: "/assets/menu/food-20.jpg", ingredients: ["Chicken Breast", "Swiss Cheese", "Bacon", "Honey Mustard", "Ciabatta"], allergens: ["Gluten", "Dairy"], rating: "4.8" },
  { id: 209, category: "Mains", name: "Astro Angus Burger", price: "$19", desc: "Premium Angus beef with caramelized onions, mushrooms, and aged cheddar.", image: "/assets/menu/food-21.jpg", ingredients: ["Angus Beef", "Aged Cheddar", "Mushrooms", "Caramelized Onions", "Brioche"], allergens: ["Gluten", "Dairy"], rating: "4.7" },
  { id: 210, category: "Mains", name: "Meteor Monster Burger", price: "$23", desc: "Triple-decker burger with three beef patties, cheese layers, and special sauce.", image: "/assets/menu/food-22.jpg", ingredients: ["Triple Beef", "Multiple Cheeses", "Lettuce", "Tomato", "Special Sauce"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "4.8" },

  { id: 211, category: "Mains", name: "Orbital Classic Burger", price: "$32", desc: "Traditional American burger cooked to perfection with classic toppings.", image: "/assets/menu/food-23.jpg", ingredients: ["Beef Patty", "American Cheese", "Lettuce", "Tomato", "Pickles", "Ketchup"], allergens: ["Gluten", "Dairy"], rating: "4.9" },
  { id: 212, category: "Mains", name: "Pulsar Peri-Peri Burger", price: "$29", desc: "Spicy chicken burger with peri-peri sauce, jalapeños, and pepper jack cheese.", image: "/assets/menu/food-24.jpg", ingredients: ["Chicken", "Peri-Peri Sauce", "Jalapeños", "Pepper Jack Cheese"], allergens: ["Gluten", "Dairy"], rating: "4.9" },
  { id: 213, category: "Mains", name: "Starship Swiss Burger", price: "$24", desc: "Beef burger with melted Swiss cheese, mushrooms, and truffle aioli.", image: "/assets/menu/food-25.jpg", ingredients: ["Beef", "Swiss Cheese", "Mushrooms", "Truffle Aioli", "Artisan Bun"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "4.7" },
  { id: 214, category: "Mains", name: "Infinite Irish Burger", price: "$22", desc: "Irish beef burger with Irish cheddar, bacon, and Guinness onions.", image: "/assets/menu/food-26.jpg", ingredients: ["Irish Beef", "Irish Cheddar", "Bacon", "Guinness Onions"], allergens: ["Gluten", "Dairy", "Alcohol"], rating: "4.8" },
  { id: 215, category: "Mains", name: "Velocity Breakfast Burger", price: "$20", desc: "Morning burger with fried egg, sausage patty, cheese, and hash brown.", image: "/assets/menu/food-27.jpg", ingredients: ["Beef", "Fried Egg", "Sausage", "Cheese", "Hash Brown"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "4.6" },
  { id: 216, category: "Mains", name: "Warp Western Burger", price: "$30", desc: "BBQ burger with fried onion rings, bacon, and smoky BBQ sauce.", image: "/assets/menu/food-28.jpg", ingredients: ["Beef", "BBQ Sauce", "Onion Rings", "Bacon", "Cheddar"], allergens: ["Gluten", "Dairy"], rating: "4.9" },
  { id: 217, category: "Mains", name: "Eclipse Hawaiian Burger", price: "$18", desc: "Teriyaki burger with grilled pineapple, bacon, and Swiss cheese.", image: "/assets/menu/food-29.jpg", ingredients: ["Beef", "Teriyaki Sauce", "Pineapple", "Swiss", "Bacon"], allergens: ["Gluten", "Dairy", "Soy"], rating: "4.6" },
  { id: 218, category: "Mains", name: "Photon Blue Cheese Burger", price: "$19", desc: "Gourmet burger with tangy blue cheese, arugula, and balsamic glaze.", image: "/assets/menu/food-30.jpg", ingredients: ["Beef", "Blue Cheese", "Arugula", "Balsamic", "Ciabatta"], allergens: ["Gluten", "Dairy"], rating: "4.8" },
  
  { id: 219, category: "Mains", name: "Cosmic Margherita Pizza", price: "$21", desc: "Classic pizza with fresh mozzarella, tomato sauce, and basil leaves.", image: "/assets/menu/food-36.jpg", ingredients: ["Pizza Dough", "Mozzarella", "Tomato Sauce", "Fresh Basil", "Olive Oil"], allergens: ["Gluten", "Dairy"], rating: "4.7" },
  { id: 220, category: "Mains", name: "Supernova Pepperoni Pizza", price: "$17", desc: "Traditional pepperoni pizza loaded with cheese and spicy pepperoni slices.", image: "/assets/menu/food-37.jpg", ingredients: ["Pizza Dough", "Mozzarella", "Pepperoni", "Tomato Sauce"], allergens: ["Gluten", "Dairy"], rating: "4.8" },

  { id: 221, category: "Mains", name: "Lunar Meat Lovers Pizza", price: "$26", desc: "Topped with pepperoni, sausage, ham, bacon, and ground beef.", image: "/assets/menu/food-38.jpg", ingredients: ["Pizza Dough", "Pepperoni", "Sausage", "Ham", "Bacon", "Beef", "Cheese"], allergens: ["Gluten", "Dairy"], rating: "4.9" },
  { id: 222, category: "Mains", name: "Meteor Veggie Supreme Pizza", price: "$20", desc: "Loaded with bell peppers, mushrooms, olives, onions, and tomatoes.", image: "/assets/menu/food-39.jpg", ingredients: ["Pizza Dough", "Bell Peppers", "Mushrooms", "Olives", "Onions", "Mozzarella"], allergens: ["Gluten", "Dairy"], rating: "4.5" },
  { id: 223, category: "Mains", name: "Astral Hawaiian Pizza", price: "$19", desc: "Ham and pineapple pizza with mozzarella and tomato sauce.", image: "/assets/menu/food-40.jpg", ingredients: ["Pizza Dough", "Ham", "Pineapple", "Mozzarella", "Tomato Sauce"], allergens: ["Gluten", "Dairy"], rating: "4.7" },
  { id: 224, category: "Mains", name: "Nebula BBQ Chicken Pizza", price: "$22", desc: "Grilled chicken with BBQ sauce, red onions, and cilantro.", image: "/assets/menu/food-41.jpg", ingredients: ["Pizza Dough", "Chicken", "BBQ Sauce", "Red Onions", "Cilantro", "Mozzarella"], allergens: ["Gluten", "Dairy"], rating: "4.8" },
  { id: 225, category: "Mains", name: "Radiant Four Cheese Pizza", price: "$38", desc: "Mozzarella, parmesan, gorgonzola, and fontina cheeses.", image: "/assets/menu/food-42.jpg", ingredients: ["Pizza Dough", "Mozzarella", "Parmesan", "Gorgonzola", "Fontina"], allergens: ["Gluten", "Dairy"], rating: "5.0" },
  { id: 226, category: "Mains", name: "Stellar Mushroom Pizza", price: "$18", desc: "Sautéed mushrooms with garlic, herbs, and three cheese blend.", image: "/assets/menu/food-43.jpg", ingredients: ["Pizza Dough", "Mushrooms", "Garlic", "Mixed Cheeses", "Herbs"], allergens: ["Gluten", "Dairy"], rating: "4.6" },
  { id: 227, category: "Mains", name: "Gravity Buffalo Chicken Pizza", price: "$21", desc: "Spicy buffalo chicken with ranch drizzle and mozzarella.", image: "/assets/menu/food-44.jpg", ingredients: ["Pizza Dough", "Chicken", "Buffalo Sauce", "Ranch", "Mozzarella"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "4.7" },
  { id: 228, category: "Mains", name: "Photon Prosciutto Pizza", price: "$34", desc: "Thin-crust pizza with prosciutto, arugula, and parmesan shavings.", image: "/assets/menu/food-45.jpg", ingredients: ["Pizza Dough", "Prosciutto", "Arugula", "Parmesan", "Olive Oil"], allergens: ["Gluten", "Dairy"], rating: "4.9" },
  { id: 229, category: "Mains", name: "Wormhole White Pizza", price: "$36", desc: "Garlic cream sauce base with ricotta, mozzarella, and spinach.", image: "/assets/menu/food-46.jpg", ingredients: ["Pizza Dough", "Ricotta", "Mozzarella", "Spinach", "Garlic", "Cream"], allergens: ["Gluten", "Dairy"], rating: "5.0" },
  { id: 230, category: "Mains", name: "Eclipse Sicilian Pizza", price: "$19", desc: "Thick-crust square pizza with tomato, anchovies, and oregano.", image: "/assets/menu/food-47.jpg", ingredients: ["Thick Pizza Dough", "Tomato Sauce", "Anchovies", "Oregano", "Mozzarella"], allergens: ["Gluten", "Dairy", "Fish"], rating: "4.7" },
  
  { id: 231, category: "Mains", name: "Velocity Carbonara Pasta", price: "$28", desc: "Creamy pasta with pancetta, egg yolk, parmesan, and black pepper.", image: "/assets/menu/food-71.jpg", ingredients: ["Spaghetti", "Pancetta", "Eggs", "Parmesan", "Black Pepper"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "4.8" },
  { id: 232, category: "Mains", name: "Starlight Spaghetti Bolognese", price: "$24", desc: "Traditional meat sauce over spaghetti with parmesan.", image: "/assets/menu/food-72.jpg", ingredients: ["Spaghetti", "Ground Beef", "Tomato Sauce", "Onions", "Parmesan"], allergens: ["Gluten", "Dairy"], rating: "4.6" },
  { id: 233, category: "Mains", name: "Quantum Alfredo Pasta", price: "$17", desc: "Fettuccine in rich cream and parmesan sauce with grilled chicken.", image: "/assets/menu/food-73.jpg", ingredients: ["Fettuccine", "Heavy Cream", "Parmesan", "Chicken", "Garlic"], allergens: ["Gluten", "Dairy"], rating: "4.5" },
  { id: 234, category: "Mains", name: "Orbital Pesto Pasta", price: "$20", desc: "Pasta tossed in fresh basil pesto with pine nuts and parmesan.", image: "/assets/menu/food-74.jpg", ingredients: ["Pasta", "Basil Pesto", "Pine Nuts", "Parmesan", "Olive Oil"], allergens: ["Gluten", "Dairy", "Tree Nuts"], rating: "4.8" },
  { id: 235, category: "Mains", name: "Cosmic Lasagna", price: "$21", desc: "Layered pasta with meat sauce, béchamel, and melted mozzarella.", image: "/assets/menu/food-75.jpg", ingredients: ["Lasagna Noodles", "Meat Sauce", "Béchamel", "Mozzarella", "Parmesan"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "4.9" },
  { id: 236, category: "Mains", name: "Pulsar Penne Arrabbiata", price: "$26", desc: "Spicy tomato sauce with garlic, chili, and fresh parsley over penne.", image: "/assets/menu/food-76.jpg", ingredients: ["Penne", "Tomatoes", "Garlic", "Chili Flakes", "Parsley"], allergens: ["Gluten"], rating: "4.7" },
  { id: 237, category: "Mains", name: "Nebula Seafood Pasta", price: "$18", desc: "Mixed seafood in garlic white wine sauce over linguine.", image: "/assets/menu/food-77.jpg", ingredients: ["Linguine", "Shrimp", "Mussels", "White Wine", "Garlic"], allergens: ["Gluten", "Shellfish", "Alcohol"], rating: "4.7" },
  { id: 238, category: "Mains", name: "Galactic Gnocchi", price: "$22", desc: "Potato dumplings in creamy tomato sauce with fresh basil.", image: "/assets/menu/food-78.jpg", ingredients: ["Potato Gnocchi", "Tomato Cream Sauce", "Basil", "Parmesan"], allergens: ["Gluten", "Dairy"], rating: "4.8" },
  { id: 239, category: "Mains", name: "Astral Mushroom Risotto", price: "$19", desc: "Creamy arborio rice with mixed mushrooms and parmesan.", image: "/assets/menu/food-91.jpg", ingredients: ["Arborio Rice", "Mushrooms", "Parmesan", "White Wine", "Butter"], allergens: ["Dairy", "Alcohol"], rating: "4.6" },
  { id: 240, category: "Mains", name: "Supernova Chicken Biryani", price: "$42", desc: "Fragrant basmati rice layered with spiced chicken, saffron, and herbs.", image: "/assets/menu/food-96.jpg", ingredients: ["Basmati Rice", "Chicken", "Saffron", "Spices", "Yogurt"], allergens: ["Dairy"], rating: "5.0" },

  // === DESSERTS (20 items) ===
  { id: 301, category: "Desserts", name: "Galactic Chocolate Cake", price: "$12", desc: "Rich chocolate layer cake with chocolate ganache frosting.", image: "/assets/menu/food-51.jpg", ingredients: ["Chocolate", "Flour", "Sugar", "Eggs", "Butter", "Cocoa"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "4.9" },
  { id: 302, category: "Desserts", name: "Dark Matter Brownie", price: "$10", desc: "Dense fudgy brownie served warm with vanilla ice cream.", image: "/assets/menu/food-52.jpg", ingredients: ["Dark Chocolate", "Butter", "Eggs", "Sugar", "Vanilla Ice Cream"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "4.9" },
  { id: 303, category: "Desserts", name: "Cheesecake Nebula", price: "$13", desc: "Creamy New York style cheesecake with berry compote.", image: "/assets/menu/food-53.jpg", ingredients: ["Cream Cheese", "Graham Crackers", "Sugar", "Eggs", "Mixed Berries"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "4.8" },
  { id: 304, category: "Desserts", name: "Quantum Tiramisu", price: "$11", desc: "Classic Italian dessert with espresso-soaked ladyfingers and mascarpone.", image: "/assets/menu/food-54.jpg", ingredients: ["Ladyfingers", "Espresso", "Mascarpone", "Cocoa", "Marsala"], allergens: ["Gluten", "Dairy", "Eggs", "Alcohol"], rating: "4.9" },
  { id: 305, category: "Desserts", name: "Stardust Apple Pie", price: "$12", desc: "Traditional apple pie with flaky crust and cinnamon.", image: "/assets/menu/food-55.jpg", ingredients: ["Apples", "Pie Crust", "Cinnamon", "Sugar", "Butter"], allergens: ["Gluten", "Dairy"], rating: "4.7" },
  { id: 306, category: "Desserts", name: "Meteor Lava Cake", price: "$14", desc: "Warm chocolate cake with molten center and raspberry sauce.", image: "/assets/menu/food-56.jpg", ingredients: ["Dark Chocolate", "Butter", "Eggs", "Sugar", "Raspberries"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "5.0" },
  { id: 307, category: "Desserts", name: "Eclipse Éclair", price: "$9", desc: "Chocolate-glazed pastry filled with vanilla custard cream.", image: "/assets/menu/food-57.jpg", ingredients: ["Choux Pastry", "Vanilla Custard", "Chocolate Ganache"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "4.6" },
  { id: 308, category: "Desserts", name: "Orbit Ice Cream Sundae", price: "$13", desc: "Three scoops of ice cream with toppings, whipped cream, and cherry.", image: "/assets/menu/food-58.jpg", ingredients: ["Ice Cream", "Chocolate Sauce", "Whipped Cream", "Cherry", "Nuts"], allergens: ["Dairy", "Tree Nuts"], rating: "4.9" },
  { id: 309, category: "Desserts", name: "Photon Fruit Tart", price: "$12", desc: "Buttery tart shell filled with custard and fresh seasonal fruits.", image: "/assets/menu/food-59.jpg", ingredients: ["Tart Shell", "Pastry Cream", "Fresh Fruits", "Glaze"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "4.7" },
  { id: 310, category: "Desserts", name: "Cosmic Crème Brûlée", price: "$11", desc: "Vanilla custard with caramelized sugar crust.", image: "/assets/menu/food-60.jpg", ingredients: ["Heavy Cream", "Egg Yolks", "Sugar", "Vanilla Bean"], allergens: ["Dairy", "Eggs"], rating: "4.8" },

  { id: 311, category: "Desserts", name: "Warp Waffle Delight", price: "$13", desc: "Belgian waffle with whipped cream, berries, and maple syrup.", image: "/assets/menu/food-61.jpg", ingredients: ["Waffle Batter", "Berries", "Whipped Cream", "Maple Syrup"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "4.8" },
  { id: 312, category: "Desserts", name: "Velocity Red Velvet Cake", price: "$10", desc: "Moist red velvet cake with cream cheese frosting.", image: "/assets/menu/food-62.jpg", ingredients: ["Cake Flour", "Cocoa", "Buttermilk", "Cream Cheese Frosting"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "4.5" },
  { id: 313, category: "Desserts", name: "Lunar Lemon Meringue Pie", price: "$11", desc: "Tangy lemon filling with fluffy meringue topping.", image: "/assets/menu/food-63.jpg", ingredients: ["Lemon Curd", "Pie Crust", "Meringue", "Sugar"], allergens: ["Gluten", "Eggs"], rating: "4.7" },
  { id: 314, category: "Desserts", name: "Stellar Carrot Cake", price: "$12", desc: "Spiced carrot cake with cream cheese frosting and walnuts.", image: "/assets/menu/food-64.jpg", ingredients: ["Carrots", "Flour", "Walnuts", "Cream Cheese Frosting"], allergens: ["Gluten", "Dairy", "Eggs", "Tree Nuts"], rating: "4.9" },
  { id: 315, category: "Desserts", name: "Asteroid Coconut Cake", price: "$11", desc: "Light coconut cake with coconut cream and shredded coconut.", image: "/assets/menu/food-65.jpg", ingredients: ["Coconut", "Flour", "Sugar", "Coconut Cream"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "4.8" },
  { id: 316, category: "Desserts", name: "Pulsar Chocolate Mousse", price: "$12", desc: "Rich and airy chocolate mousse with whipped cream.", image: "/assets/menu/food-66.jpg", ingredients: ["Dark Chocolate", "Heavy Cream", "Eggs", "Sugar"], allergens: ["Dairy", "Eggs"], rating: "4.7" },
  { id: 317, category: "Desserts", name: "Radiant Strawberry Shortcake", price: "$13", desc: "Layered sponge cake with fresh strawberries and whipped cream.", image: "/assets/menu/food-67.jpg", ingredients: ["Sponge Cake", "Strawberries", "Whipped Cream", "Sugar"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "4.9" },
  { id: 318, category: "Desserts", name: "Nebula Banana Split", price: "$10", desc: "Three scoops of ice cream with banana, toppings, and cherry.", image: "/assets/menu/food-68.jpg", ingredients: ["Ice Cream", "Banana", "Chocolate Sauce", "Nuts", "Cherry"], allergens: ["Dairy", "Tree Nuts"], rating: "4.8" },
  { id: 319, category: "Desserts", name: "Gravity Pecan Pie", price: "$9", desc: "Sweet pecan pie with flaky crust and caramel.", image: "/assets/menu/food-69.jpg", ingredients: ["Pecans", "Corn Syrup", "Pie Crust", "Butter"], allergens: ["Tree Nuts", "Gluten", "Dairy", "Eggs"], rating: "4.6" },
  { id: 320, category: "Desserts", name: "Starlight Chocolate Fondant", price: "$10", desc: "Individual chocolate cake with warm gooey center.", image: "/assets/menu/food-70.jpg", ingredients: ["Dark Chocolate", "Butter", "Eggs", "Sugar", "Flour"], allergens: ["Gluten", "Dairy", "Eggs"], rating: "4.5" },

  // === DRINKS (20 items) ===
  // Using dessert images for creamy drinks and shakes
  { id: 401, category: "Drinks", name: "Neon Chocolate Shake", price: "$10", desc: "Rich chocolate milkshake with whipped cream and chocolate drizzle.", image: "/assets/menu/food-58.jpg", ingredients: ["Chocolate Ice Cream", "Milk", "Whipped Cream", "Chocolate Sauce"], allergens: ["Dairy"], rating: "4.8" },
  { id: 402, category: "Drinks", name: "Cyber Vanilla Smoothie", price: "$8", desc: "Creamy vanilla smoothie with banana and honey.", image: "/assets/menu/food-62.jpg", ingredients: ["Vanilla Ice Cream", "Banana", "Milk", "Honey"], allergens: ["Dairy"], rating: "4.6" },
  { id: 403, category: "Drinks", name: "Plasma Fruit Milkshake", price: "$9", desc: "Mixed berry milkshake with fresh fruit toppings.", image: "/assets/menu/food-68.jpg", ingredients: ["Strawberries", "Blueberries", "Ice Cream", "Milk"], allergens: ["Dairy"], rating: "4.5" },
  { id: 404, category: "Drinks", name: "Void Mocha Frappe", price: "$6", desc: "Iced coffee blended with chocolate and topped with whipped cream.", image: "/assets/menu/food-51.jpg", ingredients: ["Coffee", "Chocolate", "Ice", "Whipped Cream"], allergens: ["Dairy"], rating: "4.7" },
  { id: 405, category: "Drinks", name: "Cosmic Caramel Latte", price: "$11", desc: "Espresso with steamed milk, caramel, and foam art.", image: "/assets/menu/food-64.jpg", ingredients: ["Espresso", "Milk", "Caramel Syrup", "Foam"], allergens: ["Dairy"], rating: "4.9" },
  { id: 406, category: "Drinks", name: "Nebula Strawberry Smoothie", price: "$8", desc: "Fresh strawberry smoothie with yogurt and granola topping.", image: "/assets/menu/food-67.jpg", ingredients: ["Strawberries", "Yogurt", "Granola", "Honey"], allergens: ["Dairy"], rating: "4.8" },
  { id: 407, category: "Drinks", name: "Galaxy Hot Chocolate", price: "$7", desc: "Rich dark chocolate with whipped cream and marshmallows.", image: "/assets/menu/food-70.jpg", ingredients: ["Dark Chocolate", "Milk", "Whipped Cream", "Marshmallows"], allergens: ["Dairy"], rating: "4.8" },
  { id: 408, category: "Drinks", name: "Meteor Mango Lassi", price: "$12", desc: "Traditional Indian mango yogurt drink with cardamom.", image: "/assets/menu/food-55.jpg", ingredients: ["Mango", "Yogurt", "Sugar", "Cardamom"], allergens: ["Dairy"], rating: "4.7" },
  { id: 409, category: "Drinks", name: "Orbit Oreo Shake", price: "$5", desc: "Cookies and cream milkshake with crushed Oreos.", image: "/assets/menu/food-69.jpg", ingredients: ["Oreo Cookies", "Vanilla Ice Cream", "Milk"], allergens: ["Dairy", "Gluten"], rating: "4.5" },
  { id: 410, category: "Drinks", name: "Stellar Strawberry Lemonade", price: "$9", desc: "Fresh strawberry lemonade with mint and ice.", image: "/assets/menu/food-63.jpg", ingredients: ["Strawberries", "Lemon", "Sugar", "Mint", "Ice"], allergens: [], rating: "4.6" },

  { id: 411, category: "Drinks", name: "Pulsar Peanut Butter Shake", price: "$11", desc: "Creamy peanut butter milkshake with chocolate chips.", image: "/assets/menu/food-66.jpg", ingredients: ["Peanut Butter", "Ice Cream", "Milk", "Chocolate Chips"], allergens: ["Dairy", "Peanuts"], rating: "4.8" },
  { id: 412, category: "Drinks", name: "Warp Waffle Shake", price: "$13", desc: "Belgian waffle blended into a milkshake with syrup.", image: "/assets/menu/food-61.jpg", ingredients: ["Waffle Pieces", "Ice Cream", "Milk", "Maple Syrup"], allergens: ["Dairy", "Gluten", "Eggs"], rating: "4.7" },
  { id: 413, category: "Drinks", name: "Eclipse Espresso", price: "$5", desc: "Double shot of rich Italian espresso.", image: "/assets/menu/food-54.jpg", ingredients: ["Espresso Beans", "Water"], allergens: [], rating: "4.6" },
  { id: 414, category: "Drinks", name: "Photon Peach Iced Tea", price: "$10", desc: "Refreshing peach-flavored iced tea with fresh fruit.", image: "/assets/menu/food-59.jpg", ingredients: ["Black Tea", "Peach", "Sugar", "Ice"], allergens: [], rating: "4.7" },
  { id: 415, category: "Drinks", name: "Velocity Vanilla Latte", price: "$12", desc: "Espresso with vanilla syrup, steamed milk, and foam.", image: "/assets/menu/food-65.jpg", ingredients: ["Espresso", "Milk", "Vanilla Syrup"], allergens: ["Dairy"], rating: "4.8" },
  { id: 416, category: "Drinks", name: "Cosmic Cappuccino", price: "$6", desc: "Classic cappuccino with perfect microfoam.", image: "/assets/menu/food-60.jpg", ingredients: ["Espresso", "Steamed Milk", "Milk Foam"], allergens: ["Dairy"], rating: "4.7" },
  { id: 417, category: "Drinks", name: "Astral Apple Cider", price: "$5", desc: "Warm spiced apple cider with cinnamon.", image: "/assets/menu/food-108.jpg", ingredients: ["Apple Juice", "Cinnamon", "Cloves", "Sugar"], allergens: [], rating: "4.4" },
  { id: 418, category: "Drinks", name: "Supernova Sparkling Lemonade", price: "$4", desc: "Fizzy lemonade with fresh lemon slices.", image: "/assets/menu/food-109.jpg", ingredients: ["Lemon", "Sparkling Water", "Sugar"], allergens: [], rating: "4.3" },
  { id: 419, category: "Drinks", name: "Radiant Rose Milk", price: "$6", desc: "Rose-flavored milk with rose petals and crushed pistachios.", image: "/assets/menu/food-110.jpg", ingredients: ["Milk", "Rose Syrup", "Rose Petals", "Pistachios"], allergens: ["Dairy", "Tree Nuts"], rating: "4.6" },
  { id: 420, category: "Drinks", name: "Lunar Butterscotch Shake", price: "$6", desc: "Sweet butterscotch milkshake with caramel topping.", image: "/assets/menu/food-56.jpg", ingredients: ["Butterscotch Ice Cream", "Milk", "Caramel"], allergens: ["Dairy"], rating: "4.7" }
];

export default extendedMenuItems;
